import Head from "next/head";
import { useRouter } from "next/router";
import { getTodos } from "../logic/database";

async function addTodo(name) {
  return fetch("/api/add-todo", {
    method: "POST",
    body: JSON.stringify({ name }),
    headers: {
      "Content-Type": "application/json",
    },
  });
}

async function toggleTodo(todoId) {
  return fetch("/api/toggle-todo", {
    method: "POST",
    body: JSON.stringify({ todoId }),
    headers: {
      "Content-Type": "application/json",
    },
  });
}

export async function getServerSideProps() {
  return {
    props: {
      todos: await getTodos(),
    },
  };
}

export default function Home({ todos }) {
  const router = useRouter();

  function handleSubmit(event) {
    event.preventDefault();
    const form = event.currentTarget;
    const data = Object.fromEntries(new FormData(form));
    addTodo(data.name).then(() => {
      router.replace(router.asPath);
      form.reset();
    });
  }

  return (
    <div className="App">
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Todo List</h1>
      <ul>
        {todos.map((todo) => {
          return (
            <li
              key={todo.id}
              style={{ textDecoration: todo.done ? "line-through" : "none" }}
              onClick={() => {
                toggleTodo(todo.id).then(() => {
                  router.replace(router.asPath);
                });
              }}
            >
              {todo.name}
            </li>
          );
        })}
      </ul>
      <form onSubmit={handleSubmit}>
        <input type="text" name="name" placeholder="New todo" required />
        <button type="submit">Add</button>
      </form>
    </div>
  );
}
